### ISSUE TITLE
Clock doesn't have space in landscape mode

### ISSUE THREAD

**Issue by alacielx** [himynameisubik/Kalm-support#51]
**Installed version:**
1.3.2

**Describe the bug**
When playing media in landscape mode pulling the notifications down shows the clock behind the now playing media controls. When Complications tweak is installed it moves lower to make space for them but not for Kalm clock.

**How to reproduce**
1. Start playing some media.
2. Turn phone to landscape mode.
3. Swipe notification drawer down.
4. Clock is behind media.

**Expected behavior**
When you pull down the notifications the media notification should be lower in order to fit the clock

**Screenshots**
![EAC23DE5-6946-45B3-9B16-2F30EBEFD5E4](https://user-images.githubusercontent.com/62450706/77212638-e58ca700-6ad5-11ea-9f80-17f6c2b32754.png)
![D610B74A-2CE1-41B4-968D-5E20DEBC3AEE](https://user-images.githubusercontent.com/62450706/77212644-e8879780-6ad5-11ea-8c94-00bc6f85d537.png)

**iOS Version:**
13.3
**Device:**
iPhone 7
**Device language:**
English

**Comment by himynameisubik** [comment]
That's weird, this was fixed in 1.3.2

**Comment by alacielx** [comment]
Disabled all other tweaks still the same result

What other information can I provide?

**Comment by himynameisubik** [comment]
Ah sorry, 1.3.3 will fix this. Was looking at the wrong ticket.

**Comment by alacielx** [comment]
Ah alright. Thank you :)

**Comment by himynameisubik** [comment]
Kalm 1.3.3 was submitted to Packix
